name: CMDL
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - pytorch=1.8.1
  - numpy=1.20.1
  - pip=21.0.1
  - python=3.8.8
  - spacy-model-en_core_web_sm=3.0.0
  - nltk=3.6.2
  - pip:
    - annoy==1.17.0
    - datasketch==1.5.3
    - elasticsearch==7.13.1
    - elasticsearch-dsl==7.3.0
    - gensim==3.8.3
    - hyperloglog==0.0.12
    - pandas==1.2.4
    - regex==2021.4.4
    - spacy==3.0.6
    - tqdm==4.49.0
    - fasttext
    - notebook
    - datasets
    - transformers
    - pillow==9.0.0